### ISSUE TITLE
Error: Cannot find module './config'

### ISSUE THREAD

**Issue by kyoto44** [nimobeeren/scrim-finder#1]
how to fix it?
Couldn't start the server

**Comment by nimobeeren** [comment]
Hi,

This happens because the config file is not included in this repository.

You should create a file `config.json` in the root diretory with content such as
```
{
  "secret": "your-secret",
  "steamApiKey": "your-api-key",
  "mongoServer": "mongodb://user:password@your-mongo-server.com"
}
```
and fill in the fields depending on your configuration. The secret can be any phrase you choose. You can get a steam API key from https://steamcommunity.com/dev/apikey. For the mongoDB server, you can use your own server or set up a free instance, for example using [Atlas](https://www.mongodb.com/cloud/atlas)
